version: 2
updates:
  # Enable version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    groups:
      bevy:
        patterns:
          - "bevy*"
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "bevy*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    reviewers:
      - "Alex-Gilbert"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "github-actions"
    reviewers:
      - "Alex-Gilbert"